#!/usr/bin/env bash
theme="~/.local/share/rofi/themes/catppuccin/deathemonic/launcher.rasi"

rofi \
	-show drun \
	-modi run,drun,ssh \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-terminal foot \
	-kb-cancel Control-q \
	-theme $theme
