#!/usr/bin/env bash
theme="~/.local/share/rofi/themes/catppuccin/deathemonic/launcher"
term="foot"

rofi \
	-show window \
	-modi run,drun,ssh \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
	-terminal $term \
	-kb-cancel Escape \
	-theme $theme
